import time
from tqdm import tqdm

print("WELCOME TO HACKERS VS COMPUTER SECURITIES")
time.sleep(2)
print("A long war is fought for decades between hackers and computer securites. Now its upon you what you'll do i.e either hack or secure")
time.sleep(6)
playername = input("Enter your name:")
time.sleep(1.5)
choice = input("What do you want to be? Hacker or Security?")
if choice == 'Hacker':
  time.sleep(2)
  print("Request accepted")
  time.sleep(1.5)
  print("Entering console...")
  time.sleep(1.5) 
  from time import sleep
  
  def loadbar(iteration, total, prefix='', suffix='', decimals=1, length=100, fill='>'):
          percent = ('{0:.' + str(decimals) + 'f}').format(100 * (iteration/float(total)))
          filledLength = int(length * iteration // total)
          bar = fill * filledLength + '-' * (length - filledLength)
          print(f'\r{prefix} |{bar}| {percent}% {suffix}', end='\r')
          if iteration == total:
            print()
    
  items = list(range(0, 50))
  l = len(items)
  
  loadbar(0, l, prefix='Progress:', suffix='Complete', length=l)
  for i, item in enumerate(items):
    time.sleep(0.1)
  loadbar(i + 1, l, prefix='Progress:', suffix='Complete', length=l)
  print("Console ready")
  print("CPU: 34%")
  print("RAM: 23%")
  usfiles = print("SECRET FILES OF US GOV")
  op = input("Hack files? yes/no:")
  if op == 'yes':
    time.sleep(1.5)
    print("Connecting to server...")
    time.sleep(1.5)
    print("Connected.")
    time.sleep(1.5)
    print("Retrieving data...")
    time.sleep(1.5)
    print("      num=1 int")
    time.sleep(1.5)
    print("      files=4")
    time.sleep(1.5)
    print("      Files loading...")
    time.sleep(1.5)
    print(" System copying files...")
    time.sleep(1.5)
    print("           67 files copied")
    time.sleep(1.5)
    print("           456 files copied")
    time.sleep(3)
    print("           ALL FILES COPIED")
    time.sleep(1.5)
    dltop = input("Delete files from its us gov archieves? yes/no:")
    if dltop == 'yes':
      time.sleep(1.5)
      print("Password required for deletion!")
      time.sleep(1.5)
      dlpass = input("To hack password, type /locate==password/1.34.256")
      time.sleep(3)
      if dlpass == '/locate==password/1.34.256':
        print("Searching...")
        time.sleep(4)
        print("13 passwords found!")
        time.sleep(1.7)
        print("Console tracing passwords...")
        time.sleep(8)
        print("******* not matched")
        print("********* not matched")
        print("******* not matched")
        print("************* not matched")
        print("**** not matched")
        print("******* not matched")
        print("********** not matched")
        print("****** not matched")
        print("******** matched")
        print("********** not matched")
        print("**** not matched")
        print("****** not matched")
        print("**** not matched")
        time.sleep(1.8)
        print("One password matched with GOV client password!")
        time.sleep(4)
        print ("Encrypting found password...")
        time.sleep(3)
        print("Password is 6667trump!!!")
        time.sleep(3)
        passenter = input("Enter password for deletion: ")
        time.sleep(1.5)
      print("Deleting files. It may take a few moments")
      time.sleep(5)
      print("Successfully deleted original files!")
      time.sleep(2)
      print("Alert! US GOV anti hacking system detected this console!")
      time.sleep(4)
      fixop = input("Hack firewall? yes/no:") 
      if fixop == 'yes':
        time.sleep(1.5)
        print("Hacking firewall...")
        time.sleep(2)
        print("Successfully hacked firewall!")
        time.sleep(1.5)
        crashop = input("Crash US GOV Anti hacking system? yes/no:")
        if crashop == 'yes':
          time.sleep(1.7)
          print("      Injecting virus...")
          time.sleep(1.7)
          print("      Virus injected!")
          time.sleep(1.7)
          print("Sending crash report to console...")
          time.sleep(1.7)
          print("System crash client is successfully installed on US GOV anti hacking system!")
          time.sleep(2)
          shareop = input("You have 20 seconds to share hacked files to base. yes/no:")
          if shareop == 'yes':
            time.sleep(1.5)
            print("Sending files to base...")
            time.sleep(1.5)
            print("       Sending client info...")
            time.sleep(3)
            print("       Files sending...")
            time.sleep(6)
            print("       Files successfully sent!")
            time.sleep(1.5)
            print("You have 10 seconds to eject console or anti hacking system will reboot!")
            time.sleep(1.5)
            ejectop = input("Eject console? yes/no:")
            if ejectop == 'yes':
              print("Succesfully ejected")
              time.sleep(3)
              print("If you liked this game please give this a star and I'm trying hard to become a software engineer. Hope you liked it give more ideas...")
elif choice == 'Security':
  time.sleep(1.5)
  
  def loadbar(iteration, total, prefix='', suffix='', decimals=1, length=100, fill='>'):
          percent = ('{0:.' + str(decimals) + 'f}').format(100 * (iteration/float(total)))
          filledLength = int(length * iteration // total)
          bar = fill * filledLength + '-' * (length - filledLength)
          print(f'\r{prefix} |{bar}| {percent}% {suffix}', end='\r')
          if iteration == total:
            print()
    
  items = list(range(0, 50))
  l = len(items)
  
  loadbar(0, l, prefix='Progress:', suffix='Complete', length=l)
  for i, item in enumerate(items):
    time.sleep(0.1)
  loadbar(i + 1, l, prefix='Progress:', suffix='Complete', length=l)
  print("Alert! Error 562: US GOV SECRET FILES IN DANGER!!!")
  time.sleep(3)
  print("FILES IN DANGER!")
  time.sleep(1.5)
  consoleop = input("Open the security console by typing SC:")
  if consoleop == 'SC':
    time.sleep(1.8)
    print("Entering security console...")
    time.sleep(4)
    print("       Opening main console...")
    time.sleep(1.5)
    print("       Alerted IT anti hackers")
    time.sleep(1.5)
    print("              Files archieve password changed...")
    time.sleep(1.5)
    print("              Ultra safe mode enabled!")
    time.sleep(1.5)
    print("Security modes enabled")
    time.sleep(3)
    firewallop = input("To enable archieve protection client, type xbc:")
    time.sleep(2)
    if firewallop == 'xbc':
      time.sleep(1.7) 
      print("Secure mode enabled.")
      time.sleep(4)
      print("Alert! Firewall client hacked! US GOV files transferring...")
      time.sleep(3)
      traceop = input("To trace firewall client hack location, type fcl:")
      time.sleep(3)
      if traceop == 'fcl':
        time.sleep(4)
        print("Searching...")
        time.sleep(2)
        print("Searching...")
        time.sleep(6)
        print("Location found!!!")
        time.sleep(1.5)
        lcop = input("To show location, type SWL")
        if lcop == 'SWL':
          print("LOCATION: 24°N -67°W 43°E -18°S")
          copop = input("To send location to special force, type sl:")
          time.sleep(1.5)
          print("Location sent...")
          print("Firewall rebooted...")
          print("File transfer cancelled...")
          print("Ultra safe mode deactivated...")
          time.sleep(3)
          exit = input("Type e to exit console:")
          if exit == 'e':
            print("Thanks for playing this . Game By Kunal-Diwan")
          
          
  
      
