[tool.poetry]
name = "project"
version = "0.1.0"
description = ""
authors = ["Kunal-Diwan <kunaldiwan1405@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
